export const BEHAVIOR_TAGS = Object.freeze({
  FIN_NIPPER: 'FIN_NIPPER',
  LONG_FIN_VULNERABLE: 'LONG_FIN_VULNERABLE',
  SLOW_SWIMMER: 'SLOW_SWIMMER',
  TERRITORIAL: 'TERRITORIAL',
  FAST_ACTIVE: 'FAST_ACTIVE',
  SHOALING: 'SHOALING',
});

export const BEHAVIOR_TAG_VALUES = Object.freeze(Object.values(BEHAVIOR_TAGS));
