name: Security Headers Verify

on:
  schedule:
    - cron: "15 9 * * 0"   # Sundays 09:15 UTC
  workflow_dispatch: {}

jobs:
  verify:
    name: Verify Cloudflare Security Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Fetch headers from apex
        run: |
          echo "Fetching headers from thetankguide.com"
          curl -sSI https://thetankguide.com > apex_headers.txt

      - name: Fetch headers from www
        run: |
          echo "Fetching headers from www.thetankguide.com"
          curl -sSI https://www.thetankguide.com > www_headers.txt

      - name: Combine and format JSON output
        run: |
          jq -n --rawfile apex apex_headers.txt --rawfile www www_headers.txt \
            --arg now "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            '{timestamp: $now, apex: $apex, www: $www}' \
            > security-headers-output.json

      - name: Upload verification artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-headers-verify
          path: security-headers-output.json

      - name: Append scheduled run entry to channel log
        if: github.event_name == 'schedule'
        run: |
          timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          echo "✅ ${timestamp} — Scheduled security headers verification completed. Artifact: security-headers-verify" >> docs/CHANNEL_LOG.md

      - name: Commit latest report into docs/security
        run: |
          mkdir -p docs/security
          mv security-headers-output.json docs/security/security-headers-verify-latest.json
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/security/security-headers-verify-latest.json docs/CHANNEL_LOG.md
          git commit -m "chore(security): update security headers verification report" || echo "No changes to commit"
          git push || echo "Push skipped (PR flow or no changes)"
