name: Security Headers Verify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # daily at 03:00 UTC

jobs:
  verify:
    name: Verify Cloudflare Security Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Fetch headers from apex
        run: |
          echo "Fetching headers from thetankguide.com"
          curl -sSI https://thetankguide.com > apex_headers.txt

      - name: Fetch headers from www
        run: |
          echo "Fetching headers from www.thetankguide.com"
          curl -sSI https://www.thetankguide.com > www_headers.txt

      - name: Combine and format JSON output
        run: |
          jq -n \
            --slurpfile apex apex_headers.txt \
            --slurpfile www www_headers.txt \
            '{timestamp: now, apex: ($apex | tostring), www: ($www | tostring)}' \
            > security-headers-output.json

      - name: Upload verification artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-headers-verify
          path: security-headers-output.json

      - name: Commit latest report into docs/security
        run: |
          mkdir -p docs/security
          mv security-headers-output.json docs/security/security-headers-verify-latest.json
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/security/security-headers-verify-latest.json
          git commit -m "chore(security): update security headers verification report" || echo "No changes to commit"
          git push || echo "Push skipped (PR flow or no changes)"
